# Generated by Django 5.1.15 on 2026-07-30 00:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aggregate_type', models.CharField(max_length=64)),
                ('aggregate_id', models.UUIDField()),
                ('event_type', models.CharField(max_length=64)),
                ('event_version', models.PositiveIntegerField(default=1)),
                ('topic', models.CharField(max_length=128)),
                ('partition_key', models.CharField(max_length=256)),
                ('tenant_id', models.UUIDField()),
                ('correlation_id', models.CharField(blank=True, default='', max_length=64)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PUBLISHED', 'Published'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'outbox_event',
                'indexes': [models.Index(fields=['status', 'created_at'], name='outbox_pending_idx')],
            },
        ),
    ]
