# Generated by Django 5.1.15 on 2026-07-30 00:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=200, null=True)),
                ('amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('reference', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('AUTHORIZED', 'Authorized'), ('CAPTURED', 'Captured'), ('VOIDED', 'Voided'), ('FAILED', 'Failed')], default='AUTHORIZED', max_length=16)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='tenants.tenant')),
            ],
            options={
                'db_table': 'payment',
                'indexes': [models.Index(fields=['tenant', 'created_at'], name='payment_tenant_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('tenant', 'idempotency_key'), name='uniq_tenant_idempotency_key')],
            },
        ),
    ]
