# Generated by Django 5.1.15 on 2026-07-31 19:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant_id', models.UUIDField()),
                ('code', models.CharField(max_length=64)),
                ('type', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('REVENUE', 'Revenue'), ('EXPENSE', 'Expense')], max_length=16)),
            ],
            options={
                'db_table': 'account',
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'code'), name='uniq_tenant_account_code')],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant_id', models.UUIDField()),
                ('event_id', models.UUIDField(unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('occurred_at', models.DateTimeField()),
                ('correlation_id', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'db_table': 'journal_entry',
                'indexes': [models.Index(fields=['tenant_id', 'created_at'], name='journal_tenant_idx')],
            },
        ),
        migrations.CreateModel(
            name='LedgerLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('direction', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=6)),
                ('amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='ledger.account')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='ledger.journalentry')),
            ],
            options={
                'db_table': 'ledger_line',
                'indexes': [models.Index(fields=['account', 'created_at'], name='line_account_idx')],
            },
        ),
    ]
